### PR TITLE
Add bazel w/ rust support and a whole lot of hackery

### PR DESCRIPTION
**Pull request by acmcarther**
@rschifflin, @seanstrom, @wmedrano

Seriously though, this makes bazel work on nix. It also sorta makes rust_rules work on nix, with one important caveat -- you have to manually patchelf the rustc that bazel pulls down. Quite unsavory, but heres what I ran.

```
 patchelf  --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" ~/.cache/bazel/_bazel_alex/137a6182ca2a00cee867ee137dbd907b/execroot/prototype3/external/rust_linux_x86_64/rustc/bin/rustc
```

That obviously will differ based on user name, project hash, and project name. Its a total PITA. I'm sure this isn't the first nix package that builds or pulls binaries -- there must be a nixy solution to this. Maybe patching bazel again to automatically patchelf anything it pulls down?

From this, i need to open three prs to three different repos:

1) Open a PR to bazelbuild/bazel to incorporate my patch in
2) Open a PR to bazelbuild/rules_rust to update their ancient rust version, and change their /bin/bash to /usr/bin/env bash. That change is (probably) not relevant here.
3) Open a PR to nixpkgs to update their version of bazel with all these fixes.

### CODE REVIEW

**Comment by seanstrom** [comment]
Woah holy shit, thanks for publishing this. Super appreciated!

**Comment by acmcarther** [comment]
@hestela: You know how long i been trying to make this work!

Here it is!

**Comment by seanstrom** [comment]
Very nice, very nice!

**Comment by acmcarther** [comment]
@seanstrom I'm not sure if you've looked into build tools like bazel or buck much. I dont know how they work with something like elm (or javascript as a whole). The idea though is that you get reproducible builds, and you can build anything that there exists a skylark rule for.

The motivation for making this work is that cargo is a bit limiting for some project organization strategies I want to play with, and managing dependencies in it is sometimes a pain. Plus, I use this tool at work, and I actually really like it. Will try to get an example rust project up shortly that shows off what this can do.

**Comment by acmcarther** [comment]
https://github.com/acmcarther/next_space_coop

Is the most basic possible thing that uses this.

**Pull request merged**
